### ISSUE TITLE
1.20.1 RequireOpCancel not worked

### ISSUE THREAD

**Issue by aleksbur** [VeiTrr/ItemClearLag-ICL#6]
/icl config set RequireOpCancel false not worked.
\config\icl\ICL.json "RequireOpCancel": false, not worked.

Players who do not have an "op" do not see the undo button to remove items.
There is also no access to the "/icl cancel" command.

**Comment by VeiTrr** [comment]
do you have permissions mod installed? e.g. luckperms, if yes, give permission through them, using icl.cancel

**Comment by aleksbur** [comment]
There was a conflict of "permissions". The problem was solved using the "LuckPerms" mod.
